# Generated by Django 5.2.8 on 2025-11-27 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('book', models.CharField(max_length=80)),
                ('risk', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('worst_case_bp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('worst_case_k', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['book'],
                'unique_together': {('pm', 'date', 'book')},
            },
        ),
    ]
