# Generated by Django 5.2.8 on 2025-11-29 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('risk', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('worst_case_bp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('worst_case_k', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_risks', to='risk.book')),
            ],
            options={
                'ordering': ['book__name'],
                'unique_together': {('book', 'date')},
            },
        ),
    ]
