# Generated by Django 5.2.8 on 2025-12-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_all_pms',
            field=models.BooleanField(default=False),
        ),
    ]
