# Generated by Django 5.2.8 on 2025-12-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_user_can_view_all_pms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookPermission',
            new_name='PMPermission',
        ),
    ]
